yagura/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from yagura.accounts.views import ProfileEditView, ProfileView, SetTimezoneView

app_name = 'accounts'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/timezone', SetTimezoneView.as_view(), name='set-timezone'),
    path(
        'social/login-error',
        TemplateView.as_view(template_name='accounts/social_error.html'),
        name='social-login-error'),
]

yagura/core/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
]

yagura/project_template/myproj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

yagura/sites/urls.py
from django.urls import path

from yagura.sites.views import (
    SiteCreateView, SiteDeleteView, SiteDetailView, SiteDisableView,
    SiteEditTitleView, SiteListView
)

app_name = 'sites'
urlpatterns = [
    path('', SiteListView.as_view(), name='list'),
    path('new', SiteCreateView.as_view(), name='create'),
    path('<uuid:pk>', SiteDetailView.as_view(), name='detail'),
    path(
        '<uuid:pk>/edittitle',
        SiteEditTitleView.as_view(),
        name='edit-title'),
    path('<uuid:pk>/_disable', SiteDisableView.as_view(), name='disable'),
    path('<uuid:pk>/delete', SiteDeleteView.as_view(), name='delete'),
]

yagura/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

# Django Debug Toolbar(optional)
if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

yagura/core/templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Yagura {% block subtitle %}{% endblock %}</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

    <link rel="stylesheet" href="{% static 'layout.css' %}">
  </head>

  <body>
    <header class="nav">
      <nav class="navbar is-fixed-top is-dark">
        <div class="navbar-brand">
          {% if request.user.is_anonymous %}
            {% url 'index' as url_brand_ %}
          {% else %}
            {% url 'sites:list' as url_brand_ %}
          {% endif %}
          <a class="navbar-item" href="{{ url_brand_ }}">
            <strong>Yagura</strong>
          </a>
          <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navMenu" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="{% url 'sites:list' %}">Sites</a>
          </div>
          <div class="navbar-end">
            {% if request.user.is_anonymous %}
              {% url 'login' as url_login_ %}
              <div class="buttons has-addons">
                <a class="button" href="{{ url_login_ }}">Log in</a>
                {% if ENABLE_PASSWORD_REGISTRATION %}
                  {% url 'registration_register' as url_register_ %}
                  <a class="button" href="{{ url_register_ }}">Register</a>
                {% endif %}
              </div>
            {% else %}
              <!-- navbar items -->
              <div class="navbar-item has-dropdown">
                <a class="navbar-link">
                  {{ request.user.full_name|default:request.user }}
                </a>
                <div class="navbar-dropdown">
                    <a class="navbar-item" href="{% url 'accounts:profile' %}">{% trans 'Profile' %}</a>
                    <a class="navbar-item" href="{% url 'logout' %}">{% trans 'Log out' %}</a>
                </div>
            </div>
            {% endif %} 
          </div>
        </div>
      </nav>

    </header>

    <main class="section">
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </main>

    <footer class="footer">
      <div class="content has-text-right">
        <p>
          Powered by <strong>Yagura v{{ YAGURA_VERSION }}</strong>
        </p>
      </div>
    </footer>

    <script>
      document.addEventListener('DOMContentLoaded', () => {
        // Get all "navbar-burger" elements
        const $navbarBurgers = Array.prototype.slice.call(
          document.querySelectorAll('.navbar-burger'), 0);
        // Check if there are any navbar burgers
        if ($navbarBurgers.length > 0) {
          // Add a click event on each of them
          $navbarBurgers.forEach( el => {
            el.addEventListener('click', () => {
              // Get the target from the "data-target" attribute
              const target = el.dataset.target;
              const $target = document.getElementById(target);
              // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
              el.classList.toggle('is-active');
              $target.classList.toggle('is-active');
            });
          });
        }
      });
    </script>
  </body>
</html>

yagura/core/templates/layouts/single_page.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="columns">
    <div class="column">
      {% block content_main %}{% endblock %}
    </div>
  </div>
{% endblock %}

yagura/core/templates/layouts/two_pane.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="columns">
    <div class="column is-one-fifth">
      <aside class="menu is-hidden-mobile">
        <ul class="menu-list">
          <li>
            <a class="nav-link" href="{% url 'sites:list' %}">
              {% trans 'List of web sites' %}
            </a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'logout' %}">
              {% trans 'Log out' %}
            </a>
          </li>
        </ul>
      </aside>
    </div>
    <div class="column">
      {% block content_main %}{% endblock %}
    </div>
  </div>
{% endblock %}

yagura/core/templates/layouts/two_pane_single.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
  <div class="columns">
    <div class="column is-one-fifth">
      <aside class="menu">
      </aside>
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
         </nav>
       </div>
    <div class="column">
      {% block content_main %}{% endblock %}
    </div>
  </div>
{% endblock %}