yagura/notifications/urls.py
from django.urls import path

from yagura.notifications.views import (
    EmailActivateView, EmailDeactivateCompleteView, EmailDeactivateView,
    EmailRecipientCreateView, EmailRecipientDeleteCompleteView,
    EmailRecipientDeleteView, EmailRecipientListView, SlackRecipientCreateView,
    SlackRecipientDeleteView, SlackRecipientListView
)

app_name = 'notifications'
urlpatterns = (
    path(
        'sites/<uuid:pk>/new',
        EmailRecipientCreateView.as_view(),
        name='add-recipient'),
    # Slack recipient urlconf
    path(
        'sites/<uuid:pk>/slack',
        SlackRecipientListView.as_view(),
        name='list-slack-recipient'),
    path(
        'sites/<uuid:pk>/slack/new',
        SlackRecipientCreateView.as_view(),
        name='add-slack-recipient'),
    path(
        'slack/<int:pk>/delete',
        SlackRecipientDeleteView.as_view(),
        name='delete-slack-recipient'),
    # Email recipient urlconf
    path(
        'sites/<uuid:pk>/email',
        EmailRecipientListView.as_view(),
        name='list-email-recipient'),
    path(
        'email/<int:pk>/delete',
        EmailRecipientDeleteView.as_view(),
        name='delete-email-recipient'),
    path(
        'delete/complete',
        EmailRecipientDeleteCompleteView.as_view(),
        name='delete-email-complete'),
    path(
        'emailactivate/<uuid:code>',
        EmailActivateView.as_view(),
        name='email-activate'),
    path(
        'emaildeactivate/<uuid:code>',
        EmailDeactivateView.as_view(),
        name='email-deactivate'),
    path(
        'emaildeactivate/complete',
        EmailDeactivateCompleteView.as_view(),
        name='email-deactivate-complete'),
)

yagura/project_template/myproj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

yagura/sites/urls.py
from django.urls import path

from yagura.sites.views import (
    SiteCreateView, SiteDeleteView, SiteDetailView, SiteDisableView,
    SiteEditTitleView, SiteListView
)

app_name = 'sites'
urlpatterns = [
    path('', SiteListView.as_view(), name='list'),
    path('new', SiteCreateView.as_view(), name='create'),
    path('<uuid:pk>', SiteDetailView.as_view(), name='detail'),
    path(
        '<uuid:pk>/edittitle',
        SiteEditTitleView.as_view(),
        name='edit-title'),
    path('<uuid:pk>/_disable', SiteDisableView.as_view(), name='disable'),
    path('<uuid:pk>/delete', SiteDeleteView.as_view(), name='delete'),
]

yagura/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

# Django Debug Toolbar(optional)
if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

yagura/sites/models.py
from http import HTTPStatus
from uuid import uuid4

from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

ALL_HTTP_STATUS = [(s.value, f"{s.value} {s.phrase}") for s in HTTPStatus]


class Site(models.Model):
    """Monitoring target site model
    """
    id = models.UUIDField(
        _('Site ID in project'), primary_key=True, default=uuid4)
    url = models.URLField(_('Site URL'))
    title = models.CharField(
        _('Site name'), max_length=50, null=True, blank=True)
    ok_http_status = models.PositiveSmallIntegerField(
        _('Excepted HTTP status code'), default=200, choices=ALL_HTTP_STATUS)
    enabled = models.BooleanField(
        _('Run monitoring?'), default=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.url

    def get_absolute_url(self):
        return f"/sites/{self.id}"

    @property
    def display_name(self):
        if self.title:
            return self.title
        return self.url

yagura/sites/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from yagura.sites.models import Site


class SiteCreateForm(forms.ModelForm):
    class Meta:
        model = Site
        fields = ['url', 'title', 'ok_http_status', ]
        widgets = {
            'url': forms.URLInput(attrs={
                'placeholder': _('If you want use basic auth, set as URL')
            })
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super().__init__(*args, **kwargs)

    def clean(self):
        # TODO: Implements method only to check site limit
        if self.request.user.is_superuser:
            return
        sites_limit = getattr(settings, 'YAGURA_SITES_LIMIT', 1)
        # 'limit is 0' mean 'no limit'
        if sites_limit == 0:
            return
        sites_count = Site.objects.filter(created_by=self.request.user).count()
        if sites_count >= sites_limit:
            raise forms.ValidationError(
                _('You are reached limits for nums of monitoring sites.'))

yagura/sites/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from yagura.monitors.services import post_disabled_monitoring
from yagura.sites.forms import SiteCreateForm
from yagura.sites.models import Site


class SiteListView(LoginRequiredMixin, ListView):
    model = Site
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        if 'all' not in self.request.GET:
            qs = qs.filter(enabled=True)
        return qs


class SiteDetailView(LoginRequiredMixin, DetailView):
    """Site detail view

    TODO: Custom 404 from request not-found pk
    """
    model = Site


# TODO: Set message
class SiteCreateView(LoginRequiredMixin, CreateView):
    model = Site
    form_class = SiteCreateForm
    initial = {
        'ok_http_status': 200,
    }

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        # TODO: Must save 'created_by' in form cobject
        site = form.instance
        site.created_by = self.request.user
        site.save()
        return super().form_valid(form)


# TODO: Set message
class SiteEditTitleView(LoginRequiredMixin, UpdateView):
    model = Site
    fields = ['title']

    def get_success_url(self):
        site = self.get_object()
        return reverse_lazy('sites:detail', args=(site.id, ))

    def get_template_names(self):
        if self.object.created_by == self.request.user:
            return ['sites/site_edittitle_form.html']
        return ['sites/site_edittitle_ng.html']

    def post(self, request, *args, **kwargs):
        site = self.get_object()
        if site.created_by == request.user:
            return super().post(request, *args, **kwargs)
        return super().get(request, *args, **kwargs)


# TODO: Set message
class SiteDisableView(LoginRequiredMixin, UpdateView):
    model = Site
    fields = ['enabled']
    success_url = reverse_lazy('sites:list')

    def get_template_names(self):
        if self.object.created_by == self.request.user:
            return ['sites/site_confirm_disable.html']
        return ['sites/site_disable_ng.html']

    def post(self, request, *args, **kwargs):
        site = self.get_object()
        if site.created_by == request.user:
            return super().post(request, *args, **kwargs)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        resp = super().form_valid(form)
        site = self.get_object()
        post_disabled_monitoring(site)
        return resp


# TODO: Set message
class SiteDeleteView(LoginRequiredMixin, DeleteView):
    model = Site
    success_url = reverse_lazy('sites:list')

    def get_template_names(self):
        if self.object.created_by == self.request.user \
                and settings.YAGURA_ENABLE_DELETING_SITES:
            return ['sites/site_confirm_delete.html']
        return ['sites/site_delete_ng.html']

    def post(self, request, *args, **kwargs):
        site = self.get_object()
        if site.created_by == request.user \
                and settings.YAGURA_ENABLE_DELETING_SITES:
            return super().post(request, *args, **kwargs)
        return super().get(request, *args, **kwargs)

yagura/sites/templates/sites/_site_overview.html
{% load static %}
{% load url_filter %}

{# Site overview for sites:site-list (row of table) #}
<div class="box" style="max-height: 150px;">
  <article class="media">
    <div class="media-left">
      <img src="{{ history.status_image_url }}">
    </div>
    <div class="media-content">
      <div class="content">
        <p>
          <strong>{{ site.display_name|guard_basic_auth }}</strong>
        </p>
        <p>
          Current status from {{ history.begin_at }}
          <a href="{% url 'sites:detail' site.id %}">
            (show detail)
          </a>
        </p>
      </div>
    </div>
  </article>
</div>

yagura/sites/templates/sites/site_confirm_delete.html
{% extends 'layouts/two_pane.html' %}
{% load url_filter %}

{% block content_main %}
  <h1 class="title">{% trans 'Confirm of deleteing site' %}</h1>
  <div class="content">
    <p>
      {% blocktrans with name=site.display_name|guard_basic_auth %}Deleting for <strong>{{ name }}</strong>{% endblocktrans %}
    </p>
    <ul>
      <!-- TODO: Localize -->
      <li>{% trans 'Delete monitoring histories together' %}</li>
      <li>{% trans 'After delete, you cannot recovery all data' %}</li>
    </ul>
    <form method="POST">
      {% csrf_token %}
      <button type="submit" class="button is-danger">{% trans 'Confirm' %}</button>
    </form>
  </div>
{% endblock %}

yagura/sites/templates/sites/site_confirm_disable.html
{% extends 'layouts/two_pane.html' %}
{% load url_filter %}

{% block content_main %}
  <h1 class="title">{% trans 'Confirm of disable monitoring site' %}</h1>
  <div class="content">
    <p>
      {% blocktrans with name=site.display_name|guard_basic_auth %}Disable monitoring for <strong>{{ name }}</strong>{% endblocktrans %}
    </p>
    <form method="POST">
      {% csrf_token %}
      <button type="submit" class="button is-danger">{% trans 'Confirm' %}</button>
    </form>
  </div>
{% endblock %}

yagura/sites/templates/sites/site_delete_ng.html
{% extends 'layouts/two_pane.html' %}
{% load url_filter %}

{% block content_main %}
  <h1 class="title">{% trans 'Deleteing site' %}</h1>
  <div class="content">
    {% if not yagura_conf.ENABLE_DELETING_SITES %}
      <p>{% trans 'Disabled deleting sites by administrator' %}</p>
    {% else %}
      <p>{% blocktrans with name=site.display_name|guard_basic_auth %}Site owner only can delete {{ name }}{% endblocktrans %}</p>
    {% endif %}
  </div>
{% endblock %}

yagura/sites/templates/sites/site_detail.html
{% extends 'layouts/two_pane.html' %}
{% load i18n %}
{% load bulma_tags %}
{% load url_filter %}

{% block content_main %}
  <div class="level">
    <h1 class="title">{% trans 'Site detail' %}: {{ site.title|default:'' }}</h1>
    {% if site.created_by == request.user %}
    <div class="btn-group" role="group">
      <a class="button is-danger is-small is-pulled-right" href="{% url 'sites:disable' site.id %}">Disable</a>
      {% if yagura_conf.ENABLE_DELETING_SITES %}
        <a class="button is-danger is-small is-pulled-right" href="{% url 'sites:delete' site.id %}">Delete</a>
      {% endif%}
    </div>
    {% endif %}
  </div>

  <h2 class="subtitle">Overview</h2>
  <div class="content">
    {# TODO: Refactor struct of site information #}
    <table class="table">
      <tbody>
        <tr>
          <th>{% trans 'Site URL' %}:</th>
          <td><a href="{{ site.url }}" target="_blank">{{ site.url|guard_basic_auth }}</a></td>
          <td></td>
        </tr>
        <tr>
          <th>{% trans 'Site name' %}:</th>
          <td>{{ site.title|default:'' }}</td>
          <td>
            <a class="button is-small" href="{% url 'sites:edit-title' site.id %}">Edit</a>
          </td>
        </tr>
        <tr>
          <th>{% trans 'Excepted HTTP status code' %}:</th>
          <td>{{ site.ok_http_status }}</td>
          <td></td>
        </tr>
        <tr>
          <th>Email notifications:</th>
          <td>
            <span class="buttons has-addons are-small">
              <a class="button" href="{% url 'notifications:list-email-recipient' site.id %}">Show</a>
              <a class="button" href="{% url 'notifications:add-recipient' site.id %}">Add</a>
            </span>
          </td>
          <td></td>
        </tr>
        <tr>
          <th>Slack notifications:</th>
          <td class="buttons has-addons are-small">
            <a class="button" href="{% url 'notifications:list-slack-recipient' site.id %}">Show</a>
            <a class="button" href="{% url 'notifications:add-slack-recipient' site.id %}">Add</a>
          </td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
  <h2 class="subtitle">History</h2>
  <div class="content">
    <table class="table is-striped is-fullwidth">
      <thead>
        <tr>
          <th>{% trans 'State' %}</th><td>{% trans 'Range' %}</td><td>{% trans 'Reason' %}</td>
        </tr>
      </thead>
      <tbody>
        {% for history in site.states.all reversed %}
        <tr>
          <td>{{ history.state }}</td>
          <td>{{ history.begin_at }} - {{ history.updated_at }} {% if forloop.first %}(now){% endif %}</td>
          <td>{{ history.reason }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

yagura/sites/templates/sites/site_disable_ng.html
{% extends 'layouts/two_pane.html' %}
{% load url_filter %}

{% block content_main %}
  <h1 class="title">{% trans 'Disable monitring site' %}</h1>
  <div class="content">
    <p>{% blocktrans with name=site.display_name|guard_basic_auth %}Site owner only can disable {{ name }}{% endblocktrans %}</p>
  </div>
{% endblock %}

yagura/sites/templates/sites/site_edittitle_form.html
{% extends 'layouts/two_pane.html' %}
{% load bulma_tags %}

{% block content_main %}
  <h1 class="title">{% trans 'Edit title of site' %}</h1>
  <div class="content">
    <form method="POST">
      {% csrf_token %}
      {{ form|bulma }}
      <div class="field">
        <button type="submit" class="button is-primary">{% trans 'Update' %}</button>
      </div>
    </form>
  </div>
{% endblock %}

yagura/sites/templates/sites/site_edittitle_ng.html
{% extends 'layouts/two_pane.html' %}
{% load url_filter %}

{% block content_main %}
  <h1 class="title">{% trans 'Edit title of site' %}</h1>
  <div class="content">
    <p>{% blocktrans with name=site.display_name|guard_basic_auth %}Site owner only can edit title of {{ name }}{% endblocktrans %}</p>
  </div>
{% endblock %}

yagura/sites/templates/sites/site_form.html
{% extends 'layouts/two_pane.html' %}
{% load bulma_tags %}

{% block content_main %}
  <h1 class="title">{% trans 'Register new site' %}</h1>
  <div class="content">
    <form method="POST">
      {% csrf_token %}
      {{ form|bulma }}
      <div class="field">
        <button type="submit" class="button is-primary">{% trans 'Register' %}</button>
      </div>
    </form>
  </div>
{% endblock %}

yagura/sites/templates/sites/site_list.html
{% extends 'layouts/two_pane.html' %}

{% block content_main %}
  <div class="columns">
    <div class="column">
      <div class="level">
        <h1 class="title">{% trans 'List of web sites' %}</h1>
        <a class="button is-link is-pulled-right" href="/sites/new">{% trans 'Add new site' %}</a>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <div class="input-group">
        {% if request.GET.all == '1' %}
          <input id="chk-site-list-all" type="checkbox" class="form-control" aria-label="Show all" checked>
        {% else %}
          <input id="chk-site-list-all" type="checkbox" class="form-control" aria-label="Show all">
        {% endif %}
        <label>Show all</label>
        <script>
          document.getElementById('chk-site-list-all').addEventListener('click', function(e) {
            if (e.target.checked) {
              location.href = '?all=1'
            } else {
              location.href = '?'
            }
          })
        </script>
      </div>
    </div>
  </div>
  <div class="columns">
    <div class="column">
      <div class="tile is-vertical">
        {% for site in site_list %}
          {% include 'sites/_site_overview.html' with site=site history=site.states.last %}
        {% endfor %}
      </div>
      <hr>
      <!-- TODO: I want to centering paginator -->
      <div>
        {% if request.GET.all == '1' %}
          {% include 'pagination.html' with getvars='&all=1' %}
        {% else %}
          {% include 'pagination.html' %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}