yagura/accounts/urls.py
from django.urls import path
from django.views.generic import TemplateView

from yagura.accounts.views import ProfileEditView, ProfileView, SetTimezoneView

app_name = 'accounts'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit', ProfileEditView.as_view(), name='profile-edit'),
    path('profile/timezone', SetTimezoneView.as_view(), name='set-timezone'),
    path(
        'social/login-error',
        TemplateView.as_view(template_name='accounts/social_error.html'),
        name='social-login-error'),
]

yagura/project_template/myproj/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

yagura/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django_registration.backends.activation.views import RegistrationView

from yagura.accounts.forms import AccountRegistrationForm

urlpatterns = [
    path('', include('yagura.core.urls')),
    path('sites/', include('yagura.sites.urls')),
    path('notifications/', include('yagura.notifications.urls')),
    path('accounts/', include('yagura.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
]

if settings.YAGURA_ENABLE_PASSWORD_REGISTRATION:
    urlpatterns += [
        path(
            'accounts/register/',
            RegistrationView.as_view(form_class=AccountRegistrationForm),
            name='registration_register'),
        path(
            'accounts/',
            include('django_registration.backends.activation.urls')
        ),
    ]

# Django Debug Toolbar(optional)
if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

yagura/accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

yagura/accounts/forms.py
import pytz
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.utils.timezone import get_current_timezone_name
from django.utils.translation import get_language
from django_registration.forms import RegistrationForm


class AccountRegistrationForm(RegistrationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email']


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['email'].required = True


# TODO: Not test
class SetLanguageForm(forms.Form):
    next = forms.URLField(widget=forms.HiddenInput)
    language = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control-sm'}),
        choices=settings.LANGUAGES)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['language'].initial = get_language()


# TODO: Not test
class SetTimezoneForm(forms.Form):
    timezone = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control-sm'}),
        choices=((tz, tz) for tz in pytz.common_timezones)
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['timezone'].initial = get_current_timezone_name()

yagura/accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView

from yagura.accounts.forms import (
    ProfileEditForm, SetLanguageForm, SetTimezoneForm
)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['language_form'] = SetLanguageForm()
        ctx['timezone_form'] = SetTimezoneForm()
        return ctx


class ProfileEditView(LoginRequiredMixin, FormView):
    """Update user profile (name and email only)

    TODO: must be verify changed email is available.
    """
    form_class = ProfileEditForm
    template_name = 'accounts/profile_edit.html'
    success_url = reverse_lazy('accounts:profile')

    def get_initial(self):
        user = self.request.user
        fields = self.form_class.Meta.fields
        return {k: getattr(user, k) for k in fields}

    def form_valid(self, form):
        user = self.request.user
        for k in self.form_class.Meta.fields:
            setattr(user, k, form.cleaned_data[k])
        user.save()
        return super().form_valid(form)


class SetTimezoneView(LoginRequiredMixin, FormView):
    form_class = SetTimezoneForm
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        self.request.session['django_timezone'] = form.cleaned_data['timezone']
        return super().form_valid(form)

yagura/accounts/templates/accounts/profile.html
{% extends 'layouts/two_pane_single.html' %}
{% load i18n %}
{% load bulma_tags %}

{% block content_main %}
  <h1 class="title">{% trans 'Profile' %}</h1>

  <h2 class="sutitle">{% trans 'Basic information' %}</h2>
  <div class="content">
    <table>
      <tbody>
        <tr><th>ID</th><td>{{ request.user.id }}</td></tr>
        <tr><th>{% trans 'Username' %}</th><td>{{ request.user.username }}</td></tr>
        <tr><th>{% trans 'Email address' %}</th><td>{{ request.user.email }}</td></tr>
        <tr><th>{% trans 'Full name' %}</th><td>{{ request.user.get_full_name }}</td></tr>
      </tbody>
    </table>
    <a class="button" href="{% url 'accounts:profile-edit' %}">
        {% trans 'Edit profile' %}
    </a>
  </div>

  <h2 class="subtitle">{% trans 'Set language' %}</h2>
  <div class="content">
    <div>
      <form class="form-inline" action="{% url 'set_language' %}" method="post">
        {% csrf_token %}
        {{ language_form|bulma_inline }}
        <button class="button" type="submit">{% trans 'Apply' %}</button>
      </form>
    </div>
  </div>

  <h2 class="subtitle">{% trans 'Set timezone' %}</h2>
  <div class="content">
    <div>
      <form class="form-inline" action="{% url 'accounts:set-timezone' %}" method="post">
        {% csrf_token %}
        {{ timezone_form|bulma_inline }}
        <button class="button" type="submit">{% trans 'Apply' %}</button>
      </form>
      </form>
    </div>
  </div>
{% endblock %}

yagura/accounts/templates/accounts/profile_edit.html
{% extends 'layouts/two_pane_single.html' %}
{% load bulma_tags %}
{% load i18n %}

{% block content_main %}
  <h1 class="title">{% trans 'Edit profile' %}</h1>
  <div class="content">
    <form method="POST">
      {% csrf_token %}
      {{ form|bulma }}
      <div class="field">
        <button type="submit" class="button is-primary">{% trans 'Submit' %}</button>
      </div>
    </form>
  </div>
{% endblock %}

yagura/accounts/templates/accounts/social_error.html
{% extends 'layouts/single_page.html' %}

{% block subtitle %}- {% trans 'Simple website monitoring' %}{% endblock %}

{% block content_section %}
  <section class="jumbotron text-center">
    <div class="container">
      <h2>Log in error</h2>
    </div>
  </section>
{% endblock %}

{% block content %}
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-8">
        </div>
      </div>
    </div>
  </div>
{% endblock %}